import { HomePage } from '@/components/home/home-page';
import Head from 'next/head';

export default function Home({ events_categories }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage events_categories={events_categories} />
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');

  return {
    props: {
      events_categories,
    },
  };
}
